# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{itunes-cli}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcus Ortiz"]
  s.date = %q{2010-12-21}
  s.default_executable = %q{itunes}
  s.description = %q{a command line interface for itunes (only supports windows/cygwin currently)}
  s.email = %q{mportiz08@gmail.com}
  s.executables = ["itunes"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "bin/itunes",
    "lib/itunes-cli.rb",
    "lib/itunes-cli/app.rb",
    "lib/itunes-cli/player.rb",
    "lib/itunes-cli/track.rb",
    "test/helper.rb",
    "test/itunes-cli/test_player.rb",
    "test/itunes-cli/test_track.rb",
    "test/test_itunes-cli.rb"
  ]
  s.homepage = %q{http://github.com/mportiz08/itunes-cli}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{a command line interface for itunes}
  s.test_files = [
    "test/helper.rb",
    "test/itunes-cli/test_player.rb",
    "test/itunes-cli/test_track.rb",
    "test/test_itunes-cli.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<optitron>, [">= 0"])
      s.add_runtime_dependency(%q<optitron>, [">= 0"])
    else
      s.add_dependency(%q<optitron>, [">= 0"])
      s.add_dependency(%q<optitron>, [">= 0"])
    end
  else
    s.add_dependency(%q<optitron>, [">= 0"])
    s.add_dependency(%q<optitron>, [">= 0"])
  end
end

